# docker-compose.yml
services:
  frontend:
    container_name: frontend
    image: ghcr.io/timaaronsharp/keepr2:latest
    labels:
      caddy.domain: domain.dev
      caddy.type: static
      caddy.mount_path: /srv/frontend

  appname:
    container_name: keepr2
    image: ghcr.io/timaaronsharp/keepr2:latest
    ports: 
      - "7045:8080"
    env_file:
      - .env.keepr2 
    labels:
      caddy.domain: ec2-54-151-10-69.us-west-1.compute.amazonaws.com
